# -*- coding: utf-8 -*-
"""StockRegression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/AgustinRedondo/38b75023f87ef5adea1c53a0535e9013/stockregression.ipynb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
from sklearn import preprocessing

df = pd.read_csv('MSFT.csv')
df['index'] = range(1, len(df) + 1)


df.head()

X = df.loc[:,['Open']].values
y = df.loc[:,'Adj Close'].values
index = df['index']
print(len(y))

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.svm import SVR
regressor1 = SVR ( kernel = 'rbf')
regressor1.fit(X_train,y_train)

y_pred1 = regressor1.predict(X) 
confidenceknn = regressor1.score(X_test, y_test)
print(confidenceknn)

plt.plot(index,y_pred1)
plt.plot(index,y)
plt.title('MSFT Stock Price')
plt.xlabel('days')
plt.ylabel('Adj Close')
plt.show()

from sklearn.ensemble import RandomForestRegressor
regressor2 = RandomForestRegressor( n_estimators = 500, random_state = 0)
regressor2.fit(X_train,y_train)

y_pred2 = regressor2.predict(X) 
confidencerfr = regressor2.score(X_test, y_test)
print(confidencerfr)

plt.plot(index,y_pred2)
plt.plot(index,y)
plt.title('MSFT Stock Price')
plt.xlabel('days')
plt.ylabel('Adj Close')
plt.show()

from sklearn.linear_model import LinearRegression
regressor3 = LinearRegression()
regressor3.fit(X_train,y_train)

y_pred3 = regressor3.predict(X) 
confidencelr = regressor3.score(X_test, y_test)
print(confidencelr)

plt.plot(index,y_pred3)
plt.plot(index,y)
plt.title('MSFT Stock Price')
plt.xlabel('days')
plt.ylabel('Adj Close')
plt.show()

